name: Generate Snake Animation

on:
  # يشتغل تلقائياً كل 12 ساعة حتى يحدّث الثعبان بآخر contributions
  schedule:
    - cron: "0 */12 * * *"

  # يسمح لك تشغّله يدوياً من تبويب Actions
  workflow_dispatch:

  # يشتغل عند أي push على الفرع الرئيسي
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # توليد الثعبان بنسختين: فاتح وغامق
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ali-791
          github_token: ${{ secrets.SNAKE_TOKEN }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # رفع الملفات المولدة إلى فرع اسمه output
      - name: Push snake SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
